### ISSUE TITLE
Default title meta-tag value does not display in the admin

### ISSUE THREAD

**Issue by momelnyk** [slate-studio/inverter#1]
If title value is not set for a Page instance, it has to be pre-populated by value of `<title>` tag.

**Comment by alexkravets** [comment]
There is not way to show default value in CMS, inverters _page_title works as a way to override title set in the template or default in the layout. Also showing this value in CMS might be not good idea, as it could be very long for SEO purpose and include website title and category title. Maybe we should add some HTML comment helper to set page title in the template, like:
